# Generated by Django 3.2.6 on 2022-06-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('dateTime', models.DateTimeField()),
                ('direction', models.CharField(max_length=5)),
                ('door', models.CharField(max_length=80)),
            ],
        ),
    ]
