# Generated by Django 3.2.6 on 2022-06-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelUploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalReport',
            new_name='tbl_Employee',
        ),
    ]
